void change_driving_car_vars();
void quit(int code);
int handle_key(SDL_Keysym keysym, SDL_Window* screen);
int process_events(SDL_Window* screen);
void audio_update();
void render();
bool render_hud();
void step_simulation(float delta);
void gen_heightmap();
void gen_map_other();
void update_static_objects();
void load_textures();
void init_collision_boxes();
void update_car_mesh();
void calculate_car_deformation();
void recalculate_normals();
void load_car(cardata& car);
void load_car_mesh(cardata& car);
void create_car_buffers();
void reset_vehicle(cardata& car);
void display_fps();
bool display_car_choose_menu();
bool display_map_choose_menu();
bool display_intro_screen();
void render_progress_bar(float progress, const std::string& text);
inline void putPixel(SDL_Surface* surf, int x, int y, Uint32 color);
bool audio_load_sound1();
bool audio_load_sound2();
void audio_start_loop();
void audio_switch_to_sound1();
void audio_switch_to_sound2();
void setup_renderer(int width, int height);
bool init_chunk(int,int,int);
void gen_chunk(int,int);
void log(std::string);
void gen_chunk_heightmap(int cx, int cy);
float gen_mountains_pixel(int sample_i, int sample_j);